#! /bin/sh

if ! [[ $1 =~ ^[1-9][0-9]*$ ]]; then
  echo "\033[31merror: PORT is not a number\033[0m"
  echo "\033[33mSyntax: $0 <PORT>\033[0m"
  exit 1
fi

lsof -i :$1 >> /dev/null
if [ $? -eq 0 ]; then
  kill $(lsof -i :$1 | awk '{ print $2 }' | uniq) &> /dev/null
  echo "\033[32mDone!\033[0m"
fi
